version: '3'


services:
  database:
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_PASSWORD: $POSTGRES_PASSWORD
      POSTGRES_USER: $POSTGRES_USER
      POSTGRES_DB: $POSTGRES_DB
      PGDATA: $PGDATA
    volumes:
      - pg-data:${PGDATA}
    ports:
      - "${POSTGRES_PORT}:${POSTGRES_PORT}"

  adminer:
    image: adminer:latest
    depends_on:
      - database
    ports:
      - "${ADMINER_PORT}:${ADMINER_PORT}"


volumes:
  pg-data: