version: '3'

services:
  database:
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_PASSWORD: $POSTGRES_PASSWORD
      POSTGRES_USER: $POSTGRES_USER
      POSTGRES_DB: $POSTGRES_DB
    volumes:
      - pg-data:${PGDATA}

volumes:
  pg-data: